public class Header extends Componente{

    public Header(int corsombreamento, int corlinha, int corfrontal, int posinicialx, int posinicialy) {
        this.setCorsombreamento(corsombreamento);
        this.setCorfrontal(corfrontal);
        this.setCorlinha(corlinha);
        this.setPosinicialx(posinicialx);
        this.setPosinicialy(posinicialy);
    }
    
    //Sobreescrita
    @Override
    public void imprimir(){
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx(), this.getPosinicialy());
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+1, this.getPosinicialy());
        Fjalp2.getTerminal().escrevaln("           _____                    _____              ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+2, this.getPosinicialy());
        Fjalp2.getTerminal().escrevaln("          /\\    \\                  /\\    \\             ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+3, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("         /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("\\____\\                /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("\\    \\            ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+4, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("        /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/    /                \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("\\    \\           ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+5, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("       /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/    /                  \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("\\    \\          ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+6, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("      /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/    /                    \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("\\    \\         ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+7, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("     /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/    /                      \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("\\    \\        ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+8, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("    /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/    /                       /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("\\    \\       ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+9, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("   /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/    /      _____    _____   /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::::::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("\\    \\      ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+10, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("  /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/____/      /\\    \\  /\\    \\ /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/\\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("\\    \\     ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+11, this.getPosinicialy());
        Fjalp2.getTerminal().escreva(" /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/    /      /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("\\____\\/");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("\\    /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/  \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("\\____\\    ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+12, this.getPosinicialy());
        Fjalp2.getTerminal().escreva(" \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("\\____\\     /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/    /\\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("\\  /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/    \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("/    /    ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+13, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("  \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("\\    \\   /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/    /  \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("\\/");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("/    / \\/____/     ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+14, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("   \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("\\    \\ /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/    /    \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::::::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("/    /              ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+15, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("    \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("\\    /");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/    /      \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("/    /               ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+16, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("     \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("\\__/");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva(":::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("/    /        \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("/    /                ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+17, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("      \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::::::::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("/    /          \\/____/                 ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+18, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("       \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::::::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("/    /                                   ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+19, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("        \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("/    /                                    ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+20, this.getPosinicialy());
        Fjalp2.getTerminal().escreva("         \\");
        Fjalp2.getTerminal().setCor(this.getCorfrontal(), this.getCorsombreamento());
        Fjalp2.getTerminal().escreva("::");
        Fjalp2.getTerminal().setCor(this.getCorlinha(), this.getCorsombreamento());
        Fjalp2.getTerminal().escrevaln("/____/                                     ");
        Fjalp2.getTerminal().setPosicaoCursor(this.getPosinicialx()+21, this.getPosinicialy());
    }
   
    
}
